module.exports = {
  login: {
    "Language": "语言",
    "login": "登录",
    "username": "用户名",
    "password": "密码",
    "register": "注册账号",
  },
  oauth_login: {
    "Language": "语言",
    "phone": "手机号码",
    "getSmsCode": "获取验证码",
    "code": "验证码",
    "confirm": "确定",
    "noaccount": "没有平台账号",
    "Language": "Languages"
  },
  oauth_register: {
    "username": "用户名",
    "phone": "手机号码",
    "getSmsCode": "获取验证码",
    "code": "验证码",
    "isagree": '我同意遵守',
    "protocol": '《泛函用户服务协议》',
    "hasusername": "已有用户名？",
    "confirm": "确定",
    "account": "关联平台账号",
    "Language": "Languages"
  },
  index: {
    "Language": "Languages"
  },
  register: {
    "username": "用户名",
    "email": "邮箱",
    "phone": "手机号码",
    "code": "验证码",
    "password": "密码",
    "repassword": "确认密码",
    "register": "注册账号",
    "account": "已有账号",
    "isagree": '我同意遵守《泛函用户服务协议》',
    "getSmsCode": "获取验证码",
  },
  usermoney: {
    "access": "如需提现，请访问官网",
    "integral": "积分:",
    "bring": "提现到",
    "exchange":"兑换提现",
    "real":"实名认证",
    "beaudited":"提现申请正在审核中",
    "mytask":"我的任务"
  },
  camera: {
    "username": "用户名",
    "age": "年龄",
    "isagree": "我同意遵守《泛函用户服务协议》",
    "exam": "示例",
    "complete": "提交",
    "id_photo": "证件照",
    "full_photo": "全身照"
  },
  camera1: {
    "upload_progreess": "上传进度：",
    "preview": "预览",
    "delete": "删除",
    "submit": "提交",
    "carpet": "地毯",
    "pet_dung": "宠物粪便",
    "waterlogging": "水渍",
    "wire": "电线",
    "pet": "宠物",
    "character": "人物",
  },
  camera2: {
    "submit": "提交",
    "age": "年龄",
  },
  camera3:{
    "lasttask":"上一步",
    "nexttask":"下一步",
    "submit":"提交",
    "progress":"上传进度:",
    "uploadvideo":"上传视频",
    "content":"请输入内容",
    "nodata":"暂无数据"
  },
  commit: {
    "id": "你的ID：",
    "username": "你的用户名：",
    "again": "再做一次",
    "submitsuccess": "任务提交成功，正在审核",
    "result": "通常会在3个小时内给出审核结果",
    "fail": "任务提交失败，请重新提交",
    "failagain": "失败了，请点击再做一次"
  },
  edit_userinfo: {
    "userimg": "用户头像",
    "username": "用户名",
    "sex": "性别",
    "birth": "出生日期",
    "location": "所在地",
    "nationality": "国籍",
    "cancel": "取消",
    "race": "种族",
    "marital": "婚姻状态",
    "mothertongue": "母语",
    "education": "学历",
    "industry": "行业",
    "income": "收入",
    "save": "保存",
    "all": "全部",
    "selectdate": "请选择日期",
    "choosesex": "请选择性别",
    "male": "男",
    "female": "女",
    "whiteperson": "白种人",
    "yellowrace": "黄种人",
    "blackrace": "黑种人",
    "unmarried": "未婚",
    "married": "已婚",
    "chinese": "汉语",
    "english": "英语",
    "junior": "初中",
    "high": "高中",
    "junirocollege": "大专",
    "undergraduate": "本科",
    "graduate": "研究生",
    "doctor": "博士",
    "internet": "互联网",
    "finance": "金融",
    "education": "教育",
    "service": "服务",
    "lessthan": "1000以下",
    "morethan": "5000以上",
    "china": "中国",
    "usa": "美国"
  },
  realname_auth: {
    "realname": "真实姓名",
    "idcard": "身份证号码",
    "submit": "提交",
    "front": "请上传正面照",
    "negative": "请上传反面照",
    "handheld": "请上传手持照"
  },
  realname: {
    "submit": "提交",
    "recertication":"重新认证",
    "front": "请上传身份证正面照",
    "negative": "请上传身份证反面照",
    "handheld": "请上传身份证手持照",
    "truename": "真实姓名",
    "idcard": "身份证号",
    "alipay": "支付宝号",
    "auditstatus":"认证审核状态：",
    "realStatus1": '审核中',
    "realStatus2": '审核通过',
    "realStatus3": '审核未通过'
  },
  widthdraw_cash: {
    "alipayname":"支付宝姓名",
    "alipayaccount":"支付宝账号",
    "integral": "积分",
    "my_points": "我的积分：",
    "txintegral": "提现积分",
    "note": "注：提现积分必须为100的倍数 / 100积分=1.00元",
    "money":"金额：",
    "submit": "提交",
    "incomes": '个人所得税',
    "incomesTit": '根据国家规定的兼职个人所得税政策，对于兼职收入中每月超过800元的部分，国家将收取其中20%的个人所得税，该部分税务会从提现金额中自动扣除，由我司代交。',
  },
  recordwav: {
    "progress": "上传进度:",
    "rerecord": "重录",
    "next": "下一步"
  },
  record:{
    "complete":"完成",
    "lasttask":"上一步",
    "nexttask":"下一步",
    "submit":"提交",
    "restart":"重录"
  },
  task_detail: {
    "type": "类型:",
    "price": "价格:",
    "cycle": "周期",
    "day": "天",
    "intro": "项目简介",
    "desc": "项目描述",
    "require": "项目要求",
    "starttask": "开始任务",
    "mysubmission":"我的提交",
    "clickview":"点击查看",
    "labelrules":"标注规则"
  },
  task_save_file: {
    "preview": "预览",
    "delete": "删除",
    "filename": "文件名",
    "submit": "提交",
    "seefile": "查看文件"
  },
  text_10qc: {
    "submit": "提交"
  },
  setting: {
    "developer": "该小程序由泛函科技开发，向其提供以下权限即可继续操作",
    "get": "获得你的",
    "record": "录音",
    "camera": "摄像头",
    "juris": "权限",
    "allow": "请允许微信获得授权"
  },
  mytask:{
    "nodata":"暂无数据哦",
    "view":"查看",
  },
  my_submission:{
    "pending":"待审核",
    "pass":"通过",
    "nopass":"拒绝",
    "nodata":"暂无数据哦",
  },
  taskrevise:{
    "lasttask":"上一步",
    "nexttask":"下一步",
    "submit":"提交",
    "progress":"上传进度:",
    "uploadvideo":"上传视频",
    "content":"请输入内容",
    "results":"质检结果：",
    "qualified":"合格",
    "failed":"不合格",
  },
  taskrevises:{
    "nodata":"还没有任务哦",
    "beaudited":"待审核",
    "pass":"通过",
    "nopass":"拒绝",
    "start":"立即做任务",
  },
  validator: {
    "oauthbindTitle": "关联平台账号",
    "oauthregisterTitle": "完善账号信息",
    "logintitle": "登录",
    "registertitle": "注册",
    "indextitle": '首页',
    "usertitle": "积分",
    "editusertitle": "编辑个人信息",
    "authentitle": "实名认证",
    "settingtitle": "设置",
    "widthdrawcashtitle": "积分提现",
    "realnametitle": "实名认证",
    "tasktitle":"我的提交",
    "agreetitle":"服务协议",
    "mysubmissiontitle":"我的提交",
    // "tasktitle":"任务详情",
    "title": "用户名/密码错误",
    "success": "登录成功",
    "notnull": "号码不能为空",
    "formaterror": "号码格式不正确",
    "notexist": "号码不存在",
    "exist": "号码已经存在",
    "sendcode": "已发送验证码",
    "getcode": "获取验证码",
    "errorphone": "手机输入不正确",
    "networkerror": "网络错误",
    "username": "用户名",
    "usernameexist": "用户名已经存在",
    "usernamemiddle": "用户名在5-30位字符",
    "namereg": "用户名须以字母开头，且只能包含字母、数字、横线及下划线",
    "phone": "手机号码",
    "phonelenerror": "手机号长度有误",
    "email": "邮箱",
    "code": "验证码",
    "correctcode": "请输入正确的验证码",
    "passwordnonull": "密码不能为空",
    "middle": "密码在6-20位字符",
    "differ": "两次密码不一致，请重新输入",
    "check": "请勾选协议信息",
    "loginsuccess": "注册成功",
    "wrong": "填写的信息有误！",
    "copysuccess": "复制成功",
    "age": "年龄",
    "uploadfail": "图片上传失败",
    "submission_success": "提交成功",
    "original": "原图",
    "compressed": "压缩图",
    "album": "从相册中选择",
    "camera": "拍照",
    // "number":"0-100的整数！",
    "agenull": "年龄不能为空",
    "sexmust": "必须选择性别",
    "modelmust": "必须选择机型",
    "picmust": "图片不能为空",
    "savesuccess": "保存成功",
    "savefail": "保存失败",
    "exists": "用户已存在",
    "networkerror": "网络错误",
    "realnamenull": "真实姓名不能为空",
    "idcardnull": "身份证号不能为空",
    "idcardmiddle": "身份证号在15-18位字符之间",
    "alipay": "支付宝号不能为空",
    "allpic": "请上传所有图片",
    "uploadsuccess": "上传成功",
    "integral": "积分不能为空",
    "integralnotenough": "积分不够啦",
    "integralsuccess": "提现成功了",
    "audit": "实名认证审核中",
    "picformat": "图片必须为jpg格式",
    "largerthan": "图片大于2M",
    "uploading": "文件正在上传",
    "tips": "提示",
    "notused": "是否允许小程序访问麦克风",
    "rerecord": "是否需要重新录音",
    "nosupport": "暂不支持该类型",
    "failget": "获取任务详情失败",
    "failapply": "申请任务失败",
    "filenull": "文件名不能为空",
    "largerthan20": "图片大于20M",
    "optionnull": "选项不能为空",
    "alipaynamenot":"支付宝姓名不能为空",
    "alipayaccountnot":"支付宝账号不能为空",
    "integralnot":"提现积分不能为空",
    "integralnumber":"积分必须输入数字",
    "integralmultiple":"积分必须是100的倍数",
    "tasknotsubmit":"任务还没有提交",
    "tashfull":"任务全部做满了",
    "taskfailture":"获取任务列表失败",
    "loadingfinish":"加载完毕了",
    "taskerror":"获取任务失败",
    "tokenfailture":"获取上传token失败",
    "submission_success": "提交成功",
    "picture":"图片",
    "audio":"音频",
    "video":"视频",
    "pleaseupload":"请上传",
    "loading":"加载数据中",
    "radionotempty":"单选不能为空",
    "multiplenotempty":"多选不能为空",
    "blanknotempty":"填空不能为空",
    "insufficient":"权限不够",
    "taskacqfailed":"任务获取失败，没有权限"
  }
}