module.exports = {
    login: {
        "Language": "Language",
        "login": "Login",
        "username": "Username",
        "password": "Password",
        "register": "Register"
    },
    oauth_login: {
        "Language": "Language",
        "phone": "Phone",
        "getSmsCode": "Send code",
        "code": "Verification Code",
        "confirm": "Confirm",
        "noaccount": "No account",
        "Language": "Languages"
    },
    oauth_register: {
        "username": "Username",
        "phone": "Phone",
        "getSmsCode": "Send code",
        "code": "Verification code",
        "isagree": 'I agree',
        "protocol": '《 Fanhan Tech User Service Protocol》',
        "hasusername": "Existing user name？",
        "confirm": "confirm",
        "account": "Linked platform account",
        "Language": "Languages",
    },
    index: {
        "Language": "Languages"
    },
    register: {
        "username": "Username",
        "email": "Email",
        "phone": "Phone",
        "code": "Verification code",
        "password": "Password",
        "repassword": "Confirm password",
        "register": "Register",
        "account": "Already had an account",
        "isagree": "I agree Fanhan Tech User Service Protocol",
        "getSmsCode": "Send code"
    },
    usermoney: {
        "access": "Please visit our website if you would like to exchange credits.",
        "integral": "Credits:",
        "bring": "Bring to the present",
        "exchange": "Exchange and cash",
        "real": "Real name authentication",
        "beaudited": "Your cash withdrawal applications is being processed.",
        "mytask": "My Task"
    },
    camera: {
        "username": "Username",
        "age": "Age",
        "isagree": "I agree Fanhan Tech User Service Protocol",
        "exam": "Sample",
        "complete": "Submit",
        "id_photo": "ID photo",
        "full_photo": "Full-length photo"
    },
    camera1: {
        "upload_progreess": "Uploading progreess：",
        "preview": "Preview",
        "delete": "Delete",
        "submit": "Submit",
        "carpet": "Carpet",
        "pet_dung": "Pet dung",
        "waterlogging": "Waterlogging",
        "wire": "Wire",
        "pet": "Pet",
        "character": "Human",
    },
    camera2: {
        "submit": "Submit",
        "age": "Age",
    },
    camera3: {
        "lasttask": "Previous",
        "nexttask": "Next",
        "submit": "Submit",
        "progress": "Upload progress:",
        "uploadvideo": "Upload Video",
        "content": "Please enter content"
    },
    commit: {
        "id": "Your ID：",
        "username": "Your name：",
        "again": "Do it again",
        "submitsuccess": "The mission is submitted successfully and is being audited",
        "result": "The result will usually be given within 3 hours",
        "fail": "Task submission failed.Please resubmit",
        "failagain": "If you fail,please click again"
    },
    edit_userinfo: {
        "userimg": "User head image",
        "username": "User name",
        "sex": "Sex",
        "birth": "Date of birth",
        "location": "Location",
        "nationality": "Nationality",
        "cancel": "Cancel",
        "race": "Race",
        "marital": "Marital status",
        "mothertongue": "Monther tongue",
        "education": "Education",
        "industry": "Industry",
        "income": "Income",
        "save": "Save",
        "all": "Whole",
        "selectdate": "Please select date",
        "choosesex": "Please choose sex",
        "male": "Male",
        "female": "Female",
        "whiteperson": "White person",
        "yellowrace": "Yellow race",
        "blackrace": "Black race",
        "unmarried": "Unmarried",
        "married": "Married",
        "chinese": "Chinese",
        "english": "English",
        "junior": "Junior middle school",
        "high": "High school",
        "junirocollege": "Junior college",
        "undergraduate": "Undergraduate",
        "graduate": "Graduate student",
        "doctor": "Doctor",
        "internet": "Internet",
        "finance": "Finance",
        "education": "Education",
        "service": "Service",
        "lessthan": "Less than 1000",
        "morethan": "More than 5000",
        "china": "China",
        "usa": "Usa"
    },
    realname_auth: {
        "realname": "Real name",
        "idcard": "Id card",
        "submit": "Submit",
        "front": "Please upload front view",
        "negative": "Please upload the negative photo",
        "handheld": "Please upload handheld photos"
    },
    realname: {
        "submit": "Submit",
        "recertication": "Re certification",
        "front": "Please upload front view",
        "negative": "Please upload the negative photo",
        "handheld": "Please upload handheld photos",
        "truename": "Real name",
        "idcard": "Id card",
        "alipay": "Alipay",
        "auditstatus": "Certification audit status：",
        "realStatus1": 'Verifying',
        "realStatus2": 'Passed',
        "realStatus3": 'Refused'
    },
    widthdraw_cash: {
        "alipayname": "Alipay name",
        "alipayaccount": "Alipay account",
        "integral": "Integral",
        "my_points": "my points：",
        "txintegral": "integral：",
        "note": "withdrawal points must be multiple of 100 / 100 integral 1.00 RMB",
        "money": "Money：",
        "submit": "Submit",
        "incomes": 'Individual income tax',
        "incomesTit": 'for income from wages and salaries, a monthly  deduction  of  800yuan shall be allowed for expensesand that part in  excess  of  800  yuanshall be the taxable income.'
    },
    recordwav: {
        "progress": "Uploading progress:",
        "rerecord": "Rerecord",
        "next": "Next"
    },
    record: {
        "complete": "Complete",
        "lasttask": "Last step",
        "nexttask": "Next step",
        "submit": "Submit",
        "restart": "Restart"
    },
    task_detail: {
        "type": "Type:",
        "price": "Price:",
        "cycle": "Cycle",
        "day": "Day",
        "intro": "Project introduction",
        "desc": "Project descipition",
        "require": "Project requirements",
        "starttask": "Start",
        "mysubmission": "My submission"
    },
    task_save_file: {
        "preview": "Preview",
        "delete": "Delete",
        "filename": "Filename",
        "submit": "Submit",
        "seefile": "File details"
    },
    text_10qc: {
        "submit": "Submit"
    },
    setting: {
        "developer": "This program is developed by Fanhan Tech",
        "get": "get your",
        "record": "record",
        "camera": "camera",
        "juris": "jurisdiction",
        "allow": "Please allow WeChat to be authorized"
    },
    mytask: {
        "nodata": "No data",
        "view": "View",
    },
    my_submission: {
        "pending": "In Review",
        "pass": "Approved",
        "nopass": "Rejected",
        "nodata": "No data",
    },
    taskrevise: {
        "lasttask": "Previous",
        "nexttask": "Next",
        "submit": "Submit",
        "progress": "Upload progress:",
        "uploadvideo": "Upload Video",
        "content": "Please enter content",
        "results": "Review status：",
        "qualified": "Approved",
        "failed": "Rejected",
    },
    taskrevises: {
        "nodata": "No tasks",
        "beaudited": "In Review",
        "pass": "Approved",
        "nopass": "Rejected",
        "start": "Start",
    },
    validator: {
        "oauthbindTitle": "Linked platform account",
        "oauthregisterTitle": "Improving account information",
        "logintitle": "Log in",
        "registertitle": "Register",
        "indextitle": 'Home',
        "usertitle": "Credits",
        "editusertitle": "Edit personal information",
        "authentitle": "Realname authentication",
        "settingtitle": "Setting",
        "widthdrawcashtitle": "Integral presentation",
        "realnametitle": "Real name authentication",
        "tasktitle": "My task",
        "agreetitle": "Service Protocol",
        "mysubmissiontitle": "My sbumission",
        // "tasktitle":"task detail",
        "title": "Username or password incorrect",
        "success": "Login success",
        "notnull": "Telephone required",
        "formaterror": "Telephone incorrect",
        "notexist": "Telephone not existed",
        "exist": "Telephone existed",
        "sendcode": "Code sent",
        "getcode": "Send code",
        "errorphone": "Telephone incorrect",
        "networkerror": "Network error",
        "username": "Username required",
        "usernameexist": "Username existed",
        "usernamemiddle": "Username is limited from 16-20 characters",
        "namereg": "The user name must start with a letter and contain only letters, numbers, crosses, and underlines",
        "phone": "Telephone required",
        "phonelenerror": "Telephone number is wrong",
        "email": "Email required",
        "code": "Code required",
        "correctcode": "Verification code incorrect",
        "passwordnonull": "Password required",
        "middle": "Password is limited from 16-20 characters",
        "differ": "Passwords do not match",
        "check": "Please choose 'I agree'",
        "loginsuccess": "Register success",
        "wrong": "Information incorrect!",
        "copysuccess": "Replicating success",
        "age": "Age required",
        "uploadfail": "Uploading failure",
        "submission_success": "Submission success",
        "original": "Original",
        "compressed": "Compressed",
        "album": "Album",
        "camera": "Camera",
        // "number":"Integer from 1-100",
        "agenull": "Age required",
        "sexmust": "Sex required",
        "modelmust": "Phone model required",
        "picmust": "Pictures required",
        "savesuccess": "Save success",
        "savefail": "Save failure",
        "exists": "User existed",
        "networkerror": "Network error",
        "realnamenull": "Real name required",
        "idcardnull": "Id card number required",
        "idcardmiddle": "Id card incorrect",
        "alipay": "Alipay required",
        "allpic": "Please upload all pictures",
        "uploadsuccess": "Uploading success",
        "integral": "Integral required",
        "integralnotenough": "The score is not enough",
        "integralsuccess": "Withdrawals successeded",
        "audit": "Real name veryfying",
        "picformat": "The picture must be in jpg format",
        "largerthan": "Picture is larger than 2M",
        "uploading": "The file is uploading",
        "tips": "Tips",
        "notused": "Please allow the app access to microphone",
        "rerecord": "Do you want to rerecord",
        "nosupport": "This task cannot be conducted on phone",
        "failget": "You do not have the authority over this task",
        "failapply": "Failture",
        "filenull": "Please enter file name",
        "largerthan20": "Picture larger than 20M",
        "optionnull": "Please choose",
        "alipaynamenot": "Please enter your real name",
        "alipayaccountnot": "Please enter Alipay account",
        "integralnot": "Please enter present integral",
        "integralnumber": "Integral must input figures",
        "integralmultiple": "The integral must be a multiple of 100",
        "tasknotsubmit": "The task has not yet been submitted",
        "tashfull": "The task is all done",
        "taskfailture": "Failed to get task list",
        "loadingfinish": "The load is finished",
        "taskerror": "Failed to get tasks",
        "tokenfailture": "Failed to upload token",
        "submission_success": "Submission success",
        "picture": " an image",
        "audio": " audio",
        "video": " video",
        "pleaseupload": "Please upload",
        "loading": "Loading",
        "radionotempty": "Radio cannot be empty",
        "multiplenotempty": "Multiple selection cannot be empty",
        "blanknotempty": "Fill in the blank cannot be empty",
        "nodata":"No data"
    }
}