export default [
  '汉语 / Manderin',
  '英语(美国) / English(US)',
  '英语(英国) / English(UK)',
  '英语(加拿大) / English(Canada)',
  '英语(澳大利亚) / English(Australia)',
  '英语(印度) / English(India)',
  '英语(新西兰) / English(New Zealand)',
  '英语(新加坡) / English(Singapore)',
  '法语(法国) / French(France)',
  '法语(北非) / French(North Africa)',
  '法语(加拿大) / French(Canada)',
  '德语 / German',
  '西班牙语(西班牙) / Spanish(Spain)',
  '葡萄牙语(葡萄牙) / Portuguese(Portugal)',
  '意大利语 / Italian',
  '阿拉伯语 / Arabic',
  '泰语 / Thai Language',
  '韩语 / Korean',
  '日语 / Japanese',
  '俄语 / Russian',
  '西班牙语(墨西哥) / Spanish(Mexico)',
  '法语(法国) / French(France)',
  '法语(北非) / French(North Africa)',
  '法语(加拿大) / French(Canada)',
  '冰岛语 / Icelandic',
  '丹麦语 / Danish',
  '瑞典语 / Swedish Language',
  '挪威语 / Norwegian Language',
  '芬兰语 / Finnish',
  '荷兰语 / Dutch',
  '加泰洛尼亚语 / Catalana',
  '捷克语 / Czech',
  '匈牙利语 / Hungarian',
  '波兰语 / Polishh',
  '希腊语 / Greek Language',
  '爱尔兰语 / Irish Language',
  '波斯语 / Farsi',
  '希伯来语 / Hebrew',
  '哈萨克语 / Kazak',
  '维语 / Uighur Language',
  '藏语 / Tibetan Language',
  '蒙语 / Mongolian',
  '马来语 / Malay Language',
  '印尼语 / Indonesian',
  '越南语 / Vietnamese Language',
  '柬埔寨语 / Cambodian',
  '缅甸语 / Burmese',
  '老挝语 / Lao Language',
  '乌克兰语 / Ukrainian',
  '印地语(印度) / Hindi',
  '巴基斯坦语 / Urdu',
  '尼泊尔 / Nepali',
  '斯里兰卡 / Sri Lankan',
  '泰米尔语(印度) / Tamil',
  '埃塞俄比亚语 / Ethiopian',
  '尼日利亚语 / Nigerian',
  '毛利语 / Maori',
  '葡萄牙语(巴西) / Portuguese(Brazil)',
  '粤语 / Cantonese',
  '斯瓦西里语(乌干达) / Kiswahili(Uganda)',
  '斯瓦西里语(坦桑尼亚) / Kiswahili(Tanzania)',
  '泰卢固语(印度) / Telugu(India)',
  '马拉泰语(印度) / Marathi(India)',
  '孟加拉语 / Bangali',
  '古吉拉特语(印度) / Gujarati(India)',
  '上海话 / Shanghai dialect'
]
